# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 00:24
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shp2svg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='poly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(dim=3, srid=4326),
        ),
    ]
